### ISSUE TITLE
cannot override "Accept" header

### ISSUE THREAD

**Issue by aboodmufti** [ryanbaldwin/Restivus#5]
I was trying to set the "Accept" header to something other than `text/html` in the `intercept()` function, but it seems like it's always being set to `application/json`. 
Thanks!

**Comment by ryanbaldwin** [comment]
Looking at it this is definitely because the Intercept is happening too soon. This seems like a simple bug and I will address it this weekend.

Thanks Abood!

**Comment by ryanbaldwin** [comment]
BOOM FIXED.
